"""Expanded music caption pools for WRIT-FM shows.

25 new instrumental + 10 new vocal captions per show.
These supplement the originals in music_bumper_generator.py.
"""

midnight_signal_new = [
    # instrumental — 25 new
    "Tangerine Dream sequencer pulses, Berlin-school kosmische, slow arpeggios dissolving into space",
    "Indonesian suling flute over tape hiss, field recording of rain, liminal and drowsy",
    "Pauline Oliveros deep listening exercise, accordion drones in a cistern, vast and still",
    "Tim Hecker style digital distortion, cathedral organ buried under static, heavenly noise",
    "Robert Rich sleep concert, slow evolving pads, binaural warmth, 4am body temperature music",
    "Alice Coltrane harp and Wurlitzer, spiritual jazz ambient, astral devotion, turiya",
    "gas-style ambient techno, Wolfgang Voigt, blurred loops, fog in a forest, Köln at dawn",
    "Éliane Radigue style, single tone shifting imperceptibly, ARP 2500 meditation, geological patience",
    "ondes Martenot solo, eerie wavering tone, 1930s electronic, ghostly and suspended",
    "Ryuichi Sakamoto late piano, sparse notes and room silence, async-era fragility",
    "oud and field recordings of wind, Middle Eastern minimalism, desert night sky",
    "Music for 18 Musicians pulse, Steve Reich, interlocking marimbas, phase shifting, patient ecstasy",
    "Biosphere style Arctic ambient, Geir Jenssen, sub-bass and ice cracking, Tromsø midnight sun",
    "Terry Riley organ drones, rainbow in curved air feeling, psychedelic minimalism",
    "Fennesz style, guitar dissolved into digital shimmer, laptop ambient, Vienna glitch-beauty",
    "mbira thumb piano solo, Shona tradition Zimbabwe, gentle metallic overtones, ancestral and calm",
    "Colleen style, music boxes and found sounds, miniature worlds, intimate and strange",
    "Lubomyr Melnyk continuous piano, cascading notes faster than thought, Ukrainian maximalism",
    "dungeon synth, lo-fi medieval synthesizer, candlelit and solitary, imaginary dark ages",
    "shakuhachi bamboo flute, Japanese Zen tradition, one breath one note, ma silence",
    "Julianna Barwick style looped vocals turned ambient, wordless human texture, cathedral layering",
    "musique concrète, Pierre Schaeffer influence, reversed bells and slowed birdsong, surreal 3am",
    "Laraaji zither and laughter meditation, celestial vibration, ambient joy at midnight",
    "synthesizer and whale song field recording, deep ocean frequencies, bioluminescent darkness",
    "sarangi drone, North Indian bowed strings, Hindustani night raga, melancholic and eternal",
    # vocal — 10 new
    {"caption": "Beach House style, dreamy female vocal, reverb guitars, slowcore shoegaze, nocturnal drift",
     "lyrics": "[verse]\nThe lighthouse went dark at two\nI kept watching anyway for you\nThe signal bends around the coast\nTransmitting to the ones we've lost\n\n[chorus]\nStill here still here still here\nWhispering to the atmosphere\nThe frequency won't let me sleep\nSome promises are mine to keep\n\n[verse]\nThe harbor seals are on the rocks\nThe tide is turning past the docks\nEach wave erases what was drawn\nAnd still the broadcast carries on"},
    {"caption": "Jeff Buckley style, aching tenor vocal, electric guitar reverb, raw emotional intensity, hallelujah energy",
     "lyrics": "[verse]\nI heard a chord that broke the lock\nOn every door on every block\nThe overtones went up so high\nThey scratched the surface of the sky\n\n[chorus]\nEverything vibrates at night\nThe frequency of fading light\nI'm tuning in to find the tone\nThat makes the loneliness feel like home\n\n[verse]\nThe river underneath the bridge\nReflects the signal from the ridge\nA voice I almost recognize\nSinging underneath the skies"},
    {"caption": "Grouper style, washed-out female vocal, layers of reverb and tape, intimate and oceanic, nightswimming",
     "lyrics": "[verse]\nThe water's dark but I can feel\nThe current pulling something real\nBeneath the surface where it's warm\nA frequency before the storm\n\n[chorus]\nDrowning in the gentlest way\nIn all the things I couldn't say\nThe night dissolves the boundary line\nBetween your silence and mine\n\n[verse]\nThe phosphorescence in the deep\nGlows for those who cannot sleep\nEach tiny light a broadcast flare\nSent to no one sent to air"},
    {"caption": "Scott Walker style, dramatic baritone, orchestral darkness, cinematic and existential, Jacques Brel influence",
     "lyrics": "[verse]\nThe chandelier sways in the draft\nOf something spoken from the aft\nOf a ship that never sailed\nA story told but never mailed\n\n[chorus]\nAt three AM the questions come\nToo large for answers too small for some\nThe night has no opinion here\nJust the ringing in my ear\n\n[verse]\nThe operator left the line\nOpen to the hum of time\nAnd I've been listening ever since\nFor evidence or eloquence"},
    {"caption": "Low style, male-female harmony, slowcore drone, spare drums, glacial sadness, patience as texture",
     "lyrics": "[verse]\nWe spoke in intervals of days\nThe silence held in different ways\nYour voice arrived on shortwave bands\nFrom frozen lakes and frozen lands\n\n[chorus]\nThe slow things matter\nThe slow things stay\nThe signal that survives decay\nIs never loud and never clear\nJust persistent year to year\n\n[verse]\nA candle measures out the dark\nIn centimeters of the wick\nThe broadcast does the same with time\nA slow dissolve a patient rhyme"},
    {"caption": "Cocteau Twins style, ethereal female glossolalia, shimmering guitars, invented language, dreamstate",
     "lyrics": "[verse]\nLumière tasovane delune\nThe silver threads of crescent moon\nErelith wandering the haze\nThrough corridors of amber days\n\n[chorus]\nSovanel etherine\nThe space between the space between\nDeluvian the midnight shore\nA frequency forevermore\n\n[verse]\nCascavel the breathing light\nFoluminant the edge of night\nEach syllable a key that turns\nThe lock on everything that yearns"},
    {"caption": "Adrianne Lenker style, fragile female vocal, barely-there acoustic guitar, intimate as a whisper, wounded beauty",
     "lyrics": "[verse]\nThe moth against the window screen\nTrying to reach the bluish green\nLight of the radio dial\nI've been sitting here a while\n\n[chorus]\nSomething about the hour is true\nSomething about the static too\nThe way it sounds like breathing when\nThe world resets and starts again\n\n[verse]\nMy tea went cold an hour past\nThe night is moving slow and fast\nAt once like time does when you're still\nPerched on the edge of the windowsill"},
    {"caption": "Thom Yorke acoustic, fragile falsetto, piano and strings, vulnerability and grandeur, suspended",
     "lyrics": "[verse]\nThe satellites above my head\nAre saying things I never said\nBouncing signals through the void\nEvery frequency deployed\n\n[chorus]\nAm I the listener or the sound\nThe signal or the lost and found\nAt midnight everything's the same\nAnonymous without a name\n\n[verse]\nI press my ear against the floor\nAnd hear the building breathe and snore\nA hundred lives stacked in the dark\nEach one a radio each one a spark"},
    {"caption": "Agnes Obel style, clear alto female vocal, piano and cello, Nordic melancholy, precise and ghostly",
     "lyrics": "[verse]\nThe metronome inside the wall\nKeeps time for no one after all\nIts clicking neither fast nor slow\nJust the tempo of the undertow\n\n[chorus]\nPhilosophy at 3AM\nIs just the night asking when\nYou'll finally stop thinking through\nThe distance between me and you\n\n[verse]\nThe candelabra drips its wax\nOn letters I won't ever fax\nThe questions land like falling snow\nToo gentle for the ground below"},
    {"caption": "Talk Talk spirit of Eden style, Mark Hollis whisper-vocal, sparse jazz improvisation, post-rock genesis",
     "lyrics": "[verse]\nThe colour of the spring was grey\nThe kind that takes your breath away\nNot sadness but the space before\nA silence opening a door\n\n[chorus]\nAfter the flood the instruments\nLay scattered like a evidence\nOf something that was played and felt\nThe ice the music chose to melt\n\n[verse]\nOne note hangs in the studio air\nA microphone with time to spare\nThe tape runs on the red light glows\nThe song arrives and no one knows"},
]

the_night_garden_new = [
    # instrumental — 25 new
    "Diamanda Galás style, extreme operatic wail, piano dissonance, gothic horror, blood and cathedral",
    "nyckelharpa medieval Swedish fiddle, droning strings, forest ritual, ancient Scandinavian darkness",
    "theremin and pipe organ duet, 1950s horror film score, cobwebs and candelabra",
    "ney flute and darbuka, Ottoman night music, minor key, Sufi trance after midnight",
    "Bohren und der Club of Gore style, doom jazz, glacial saxophone, noir darkness",
    "hurdy-gurdy drone, French medieval troubadour, processional and funereal, plague music",
    "Ligeti Atmosphères influence, dense orchestral cluster, 2001 monolith energy, terrifying beauty",
    "Atrium Carceri style dark ambient, dungeon reverb, chains and water dripping, subterranean",
    "gagaku court music, Japanese imperial tradition, shō mouth organ, eerie and ceremonial",
    "vibraphone and bowed bass, noir jazz, Blue Velvet soundtrack mood, unsettling beauty",
    "Coil-style experimental industrial, time machines, pastoral and menacing simultaneously",
    "Iannis Xenakis string glissandi, architectural sound, tense and mathematical, dark geometry",
    "erhu and thunderstorm field recording, Chinese bowed strings, weeping through rain",
    "krummhorn and crumhorn consort, Renaissance dance of death, medieval woodwinds, archaic",
    "Eleni Karaindrou film score style, melancholic oboe and strings, Greek landscape at night",
    "duduk and cello, Armenian-European mourning, Djivan Gasparyan influence, ancient sorrow",
    "Mica Levi Under the Skin style, alien strings, detuned and predatory, beautiful menace",
    "church bells recorded and slowed 800 percent, metallic drones, spectral resonance",
    "African balafon in minor key, dark malinké melody, nocturnal West African mystery",
    "glass harmonica and contrabassoon, Benjamin Franklin instrument meets lowest woodwind, uncanny",
    "Hildur Guðnadóttir style, solo cello with electronics, Chernobyl atmosphere, dread and beauty",
    "taiko drums at half speed, massive reverb, Japanese thunder god energy, seismic ritual",
    "cristal baschet and waterphone, unusual acoustic instruments, metallic singing, otherworldly",
    "Estonian choir in minor key, Arvo Pärt Kanon Pokajanen influence, penitential and vast",
    "barrel organ playing backwards, fairground at 3am, circus of the uncanny",
    # vocal — 10 new
    {"caption": "Kate Bush style, dramatic soprano, art-pop with harpsichord, gothic fairy tale, theatrical",
     "lyrics": "[verse]\nThe ivy climbs the iron gate\nI arrive an hour too late\nThe garden's locked but I can hear\nA melody that draws me near\n\n[chorus]\nRunning up the hill of thorns\nWhere the midnight flower's born\nIf I could make a deal with night\nI'd trade the day for second sight\n\n[verse]\nThe foxglove whispers to the yew\nA poison lullaby for two\nEvery berry every bark\nGlows luminous inside the dark"},
    {"caption": "Diamanda Galás style, operatic female vocal, extreme range, dark piano, gothic avant-garde terror",
     "lyrics": "[verse]\nThe plague bell rings across the moor\nA sound I've always listened for\nThe insects hum in minor thirds\nAnd death arrives without the words\n\n[chorus]\nO the garden eats the dead\nRoses growing where they bled\nEvery grave becomes a bed\nFor the flowers overhead\n\n[verse]\nThe nightshade and belladonna bloom\nPerfuming every shuttered room\nThe beautiful and poisonous\nAre always synonymous"},
    {"caption": "Zola Jesus style, post-industrial soprano, dark synths, Eastern European intensity, cathedral goth",
     "lyrics": "[verse]\nThe icons weep in the chapel wall\nGold leaf peeling in the hall\nA candle gutters, shadows leap\nAcross the faces of the deep\n\n[chorus]\nSanctus, sanctus the void replies\nTo every prayer that upward flies\nThe night garden has no god\nJust the turning of the sod\n\n[verse]\nI kneel but not to anything\nExcept the way the darkness sings\nA hymn with neither words nor end\nAround each corner, past each bend"},
    {"caption": "Nico style, deep female vocal, harmonium drone, Marble Index era, Germanic and funereal",
     "lyrics": "[verse]\nThe frozen roses on the wall\nRemember nothing after all\nThe frost preserves but doesn't keep\nThe dream alive inside the sleep\n\n[chorus]\nJanitor of lunacy\nTend the garden after me\nWhen the last petal has curled\nClose the gate upon the world\n\n[verse]\nThe cypress trees are pointing up\nLike fingers of a buried cup\nReaching through the cemetery earth\nTo measure darkness by its worth"},
    {"caption": "Lisa Gerrard style, wordless contralto, Dead Can Dance influence, ancient ritual, glossolalic mourning",
     "lyrics": "[verse]\nAvaneros delume shan\nThe torches carried by each hand\nProcesiva del oscur\nThe garden opens to the pure\n\n[chorus]\nLamentasa voreign\nThe ritual begins again\nDescarava luminé\nThe darkness is the oldest prayer\n\n[bridge]\nO salvatier nocturne\nThe roots descend the branches turn\nEnveloria sanctefiend\nBetween the worlds the garden dreams"},
    {"caption": "PJ Harvey style, raw female vocal, detuned guitar, moor and heath, English gothic, visceral",
     "lyrics": "[verse]\nThe bones of rabbits in the field\nThe harvest that the earth won't yield\nI walked the furrow after rain\nAnd pulled the darkness up again\n\n[chorus]\nGrow me something terrible\nSomething old and horrible\nIn the plot behind the house\nQuiet as a church mouse\n\n[verse]\nThe scarecrow turned its head last night\nI swear it did in the half-light\nThe crows don't fear it anymore\nThey perch on what it's standing for"},
    {"caption": "Fever Ray style, pitch-shifted vocal, dark electronic, Scandinavian witch-pop, masks and ritual",
     "lyrics": "[verse]\nI painted my face with the ash\nOf the fire that burned the cash\nIn the clearing past the stones\nWhere the forest keeps its bones\n\n[chorus]\nIf I had a voice like soil\nIf my blood were made of oil\nI would sing the garden open\nEvery gate and every token\n\n[verse]\nThe children left their shoes outside\nThe door the mushroom circle wide\nEnough for dancing in the rain\nThe night they never came back again"},
    {"caption": "Current 93 style, David Tibet spoken-sung, acoustic folk horror, English apocalyptic pastoral",
     "lyrics": "[verse]\nIn the garden of the black sun\nWhere the horse's work is done\nThe imperium of flowers falls\nAcross the crumbling abbey walls\n\n[chorus]\nAll the pretty little horses\nAll the pretty little corpses\nGrowing poppies from their eyes\nUnderneath the Christian skies\n\n[verse]\nThe corn dolly in the field\nKnows the secret of the yield\nThat everything must go to ground\nBefore the newer world is found"},
    {"caption": "Anna von Hausswolff style, organ-driven dark art-pop, Swedish soprano, monumental and haunting",
     "lyrics": "[verse]\nThe organ pipes are thirty feet\nOf hollowed tin and hammered sheet\nEach note a column in the nave\nA sound that stretches past the grave\n\n[chorus]\nCeremony ceremony\nThis is not a testimony\nThis is just the building's breath\nThe architecture after death\n\n[verse]\nI press the keys and walls vibrate\nThe plaster cracks the windows shake\nTo make a sound this deep this low\nYou have to let your whole self go"},
    {"caption": "Lingua Ignota style, extreme female vocal, classical piano meets noise, beautiful agony",
     "lyrics": "[verse]\nThe garden speaks in thorn and root\nIn the language of disputed fruit\nEach blossom is a wound that heals\nEach thorn reminds you how it feels\n\n[chorus]\nCaligula's garden grows\nIn the place that no one goes\nWhere the beautiful and cruel\nAre the flower and the fuel\n\n[verse]\nI tend these beds with bleeding hands\nThe soil obeys but never understands\nWhy everything that's grown with care\nStill carries venom in the air"},
]

dawn_chorus_new = [
    # instrumental — 25 new
    "Wes Montgomery octave guitar, warm morning tone, jazz standard feel, coffee shop elegance",
    "bouzouki and accordion, Greek island morning, Aegean sea breeze, whitewashed walls",
    "erhu and guzheng duet, Chinese silk string ensemble, morning mist over mountains",
    "Nils Frahm All Melody style, felt piano and harmonium, first light, gentle mechanism",
    "Erik Satie Gymnopédies influence, slow spare piano, morning reverie, Parisian solitude",
    "fingerstyle acoustic guitar, Leo Kottke influence, American pastoral, barn at sunrise",
    "balalaika trio, Russian folk morning song, troika through birch forest, brisk and cheerful",
    "uilleann pipes and concertina, Irish pastoral, green hills at dawn, gentle and ancient",
    "marimba solo, West African and Central American resonance, wooden warmth, sunlight on leaves",
    "recorder consort, Renaissance morning aubade, gentle polyphony, courtyard at first light",
    "Toumani Diabaté kora solo, intricate West African harp, morning griot, golden and generous",
    "alto flute and harp duo, impressionist shimmer, Ravel influence, garden at 7am",
    "mandolin and guitar, Italian morning, Neapolitan melody, balcony overlooking the sea",
    "mbira and marimba, Zimbabwean morning, Stella Chiweshe influence, ancestral sunrise",
    "Dave Brubeck odd-time jazz piano, Take Five energy, sophisticated and swinging, breakfast club",
    "sitar morning raga, Ravi Shankar influence, Raga Todi, meditative and devotional, pre-dawn",
    "clawhammer banjo solo, old-time Appalachian, fog lifting from hollers, rural dawn",
    "vibraphone and upright bass, West Coast cool jazz, 1955, easy and sophisticated",
    "santur hammered dulcimer, Persian morning mode, Isfahan awakening, intricate and bright",
    "classical violin partita, solo Bach feeling, morning practice, discipline and beauty",
    "cajón and nylon guitar, Spanish flamenco rumbas, Mediterranean morning, café terrace",
    "accordion musette waltz, Parisian morning, Amélie soundtrack feel, whimsical and warm",
    "dan tranh zither, Vietnamese morning music, mekong delta sunrise, silk and water",
    "thumb piano kalimba and birdsong field recording, garden awakening, Africa meets nature",
    "Oscar Peterson trio energy, swinging piano and walking bass, joyful virtuosity, brunch",
    # vocal — 10 new
    {"caption": "Vinicius de Moraes and Toquinho style, Portuguese vocal, bossa nova guitar, morning in Rio, poetic",
     "lyrics": "[verse]\nThe morning comes like bossa nova\nGentle as a lover's shoulder\nThe coffee steams the window fogs\nSão Paulo wakes its sleeping dogs\n\n[chorus]\nBom dia to the bread and light\nTo everything that survived the night\nThe morning has no enemies\nJust the hum of mango trees\n\n[verse]\nThe fisherman is on the bay\nHis net spread out to greet the day\nEach silver catch a small hello\nFrom the ocean down below"},
    {"caption": "Joni Mitchell style, clear soprano, open-tuned guitar, morning confessional, blue and gold",
     "lyrics": "[verse]\nI painted my morning orange and blue\nThe way the light fell I could see right through\nThe curtain to the maple tree\nWhere a robin sang its aubade free\n\n[chorus]\nMorning is a gallery\nOf shadows turning gold for free\nYou just have to be awake\nFor the exhibition's sake\n\n[verse]\nThe clouds are doing Rorschach tests\nAbove the bakery heading west\nI see a horse I see a door\nI see the day worth waking for"},
    {"caption": "Nick Mulvey style, fingerpicked nylon guitar, gentle male vocal, world-folk, morning pilgrimage",
     "lyrics": "[verse]\nThe kettle sings its one-note song\nThe morning stretches slow and long\nA pigeon on the chimney stack\nIs calling all the daylight back\n\n[chorus]\nFirst light, first breath, first cup\nThe whole world slowly opening up\nLike a flower that forgot it closed\nNow remembering the sun it knows\n\n[verse]\nThe postman passes at the gate\nMy neighbor waves, she's running late\nThe ordinary is the gift\nThe morning gives us when we drift"},
    {"caption": "Eva Cassidy style, warm alto vocal, acoustic guitar, gospel-folk tenderness, gentle sunrise power",
     "lyrics": "[verse]\nSomewhere over the rooftops grey\nThe blue is pushing through the fray\nA patch of sky no bigger than\nThe hope inside a tired man\n\n[chorus]\nFields of gold in the morning hour\nEvery blade a tiny tower\nCatching light and holding on\nTo the melody of dawn\n\n[verse]\nThe school bus rumbles down the street\nThe crossing guard in the morning heat\nIs waving like she's conducting all\nThe children through the morning's hall"},
    {"caption": "José González style, Swedish-Argentine folk, nylon guitar, quiet male vocal, contemplative morning",
     "lyrics": "[verse]\nThe frost is melting on the glass\nThe night is finally going to pass\nA sparrow bounces on the wire\nSinging to a higher choir\n\n[chorus]\nStep out step out into the day\nLeave the heavy dreams to stay\nIn the bed where they belong\nThe morning needs a different song\n\n[verse]\nThe bicycle is by the door\nThe route I've ridden times before\nBut every morning something's changed\nThe light has rearranged"},
    {"caption": "Madeleine Peyroux style, smoky female jazz vocal, brushed drums and bass, morning café, tender",
     "lyrics": "[verse]\nAnother sunrise at the bar\nThe coffee's closer than the car\nThe bartender is pouring cream\nInto the last of someone's dream\n\n[chorus]\nBetween the last drink and the first\nThe morning satisfies the thirst\nFor something simple, something true\nA melody I always knew\n\n[verse]\nThe newspaper is yesterday's\nThe crossword filled in different ways\nThe jazz is playing low and sweet\nThe morning tapping both its feet"},
    {"caption": "Caetano Veloso unplugged style, Brazilian Portuguese vocal, gentle nylon guitar, morning tenderness",
     "lyrics": "[verse]\nA janela aberta ao sol\nThe window open to the sky\nThe morning sings in Portuguese\nA language made for days like these\n\n[chorus]\nDevagar, devagar\nSlowly like the morning star\nThere's no hurry when the light\nIs this gentle this polite\n\n[verse]\nThe papaya on the plate\nThe morning never makes you wait\nIt simply arrives and fills the room\nWith the opposite of gloom"},
    {"caption": "Gregory Porter style, warm baritone jazz vocal, piano and horns, soulful morning, gospel undertow",
     "lyrics": "[verse]\nThe dawn is liquid gold today\nPouring down the Milky Way\nInto my cup into my street\nOnto the shoes on my two feet\n\n[chorus]\nBe good to the morning and\nThe morning will extend a hand\nA warm one, like your mama's was\nThe morning loves you just because\n\n[verse]\nI heard a saxophone at six\nComing from the brownstone bricks\nSomeone practicing their scales\nLike prayer that never fails"},
    {"caption": "Esperanza Spalding style, agile female jazz vocal, upright bass, playful and virtuosic, sunrise swing",
     "lyrics": "[verse]\nThe bass line walks me out of bed\nA melody inside my head\nThat wasn't there when I fell asleep\nThe kind of song the morning keeps\n\n[chorus]\nDo re mi the sun is up\nFa so la I'll fill my cup\nTi do the day begins to swing\nAnd every bird has learned to sing\n\n[verse]\nThe mirror says good morning back\nThe cat is stretching on the mat\nThe world is tuning up again\nA symphony from eight to ten"},
    {"caption": "Angélique Kidjo style, powerful West African female vocal, joyful morning energy, Beninese sunshine",
     "lyrics": "[verse]\nThe rooster calls the market wakes\nThe bread is in the oven bakes\nAcross the compound children run\nToward the first bread toward the sun\n\n[chorus]\nBon matin the world is new\nEvery morning born in blue\nThen gold then green then wide awake\nThe morning's ours for us to take\n\n[verse]\nThe grandmother is sweeping stones\nA rhythm older than the bones\nOf the baobab by the road\nWho carries everybody's load"},
]

sonic_archaeology_new = [
    # instrumental — 25 new
    "Khmer rock, Cambodian garage psychedelia, 1960s Phnom Penh, Sinn Sisamouth era, farfisa organ",
    "Peruvian huayno, charango and quena flute, Andean highlands, 1970s Discos Smith pressing",
    "Congolese rumba guitar, Franco and TPOK Jazz style, intricate fingerpicking, Kinshasa 1960s",
    "Zamrock, Witch band style, Zambian psychedelic rock, fuzz guitar and Bemba vocals, 1975",
    "Highlife guitar, ET Mensah style, Ghana 1950s, jazzy horns and palm wine warmth",
    "Pakistani film music, Lollywood soundtrack, sitar and strings, Lahore 1970s melodrama",
    "Balearic DJ mix feel, José Padilla Café del Mar, sunset Ibiza 1990, eclectic and warm",
    "exotica, Martin Denny style, fake tropical birds and vibraphone, 1957 tiki lounge fantasy",
    "Northern soul floor-filler, uptempo Motown rarity, stomping beat, Wigan Casino energy",
    "Portuguese fado instrumental, guitarra Portuguesa, Coimbra style, melancholic virtuosity",
    "Hailu Mergia style, Ethiopian keyboard wizard, accordion and synth, Addis nightclub 1985",
    "Bollywood qawwali disco, devotional Sufi singing meets Mumbai dancefloor, Nusrat meets RD Burman",
    "calypso, Lord Kitchener style, steel pan and brass, Trinidad 1950s, carnival energy",
    "Thai luk thung, country music of Thailand, molam influence, Isan region, 1970s heartbreak",
    "Somali funk, Dur Dur Band style, Mogadishu 1980s, synth bass and pentatonic guitar",
    "surf rock instrumental, Dick Dale wet reverb guitar, 1962, waves and tremolo bar",
    "kosmische Popol Vuh style, synthesizer and acoustic guitar, Bavarian cosmic, Aguirre soundtrack",
    "boogie, Zapp and Roger style, talkbox and synth funk, early 1980s electro-funk",
    "rebetiko instrumental, Greek urban blues, bouzouki and baglamas, 1930s Piraeus underworld",
    "South African mbaqanga, mahlathini style, groaner bass vocal energy, township jive, 1970s",
    "Tuareg wedding guitar, Mdou Moctar influence, Saharan hypnotic picking, Niger celebration",
    "Pakistani qawwali, Nusrat Fateh Ali Khan influence, harmonium and tabla, devotional ecstasy",
    "mento, Jamaican folk calypso, pre-ska acoustic, banjo and rumba box, 1950s Kingston",
    "Czechoslovak jazz, SHQ style, Prague 1960s, cool jazz behind the Iron Curtain",
    "Cape Verdean funaná, accordion and ferrinho, Cabo Verde party music, Atlantic Islands groove",
    # vocal — 10 new
    {"caption": "Os Mutantes style tropicália, Portuguese vocal, psychedelic guitar, Brazilian chaos-pop, 1968",
     "lyrics": "[verse]\nThe record melted in the sun\nIn a São Paulo afternoon\nThe groove is warped but still it plays\nA revolution in a haze\n\n[chorus]\nEverything is everything\nThe parrot and the satellite sing\nThe future and the past collide\nOn the B-side of the B-side\n\n[verse]\nA synthesizer made of fruit\nA guitar in a parachute\nThe tropics ate the avant-garde\nAnd left its bones in the backyard"},
    {"caption": "Oum Kalthoum influence, Arabic female vocal, oud and qanun, Egyptian classical, 1960s Cairo grandeur",
     "lyrics": "[verse]\nThe concert lasted until dawn\nFour hours and she'd barely drawn\nA breath between the notes she bent\nEach phrase a continent\n\n[chorus]\nThe tape is worn the grooves are thin\nBut still the voice comes flooding in\nAcross the decades through the dust\nA love too large for any trust\n\n[verse]\nThe violins were twenty strong\nThe audience sang every song\nFrom memory and from the heart\nThe archaeology of art"},
    {"caption": "Miriam Makeba style, South African vocal, Click Song energy, jazz and folk, apartheid-era resistance beauty",
     "lyrics": "[verse]\nThe record smuggled through the port\nA sound the censors tried to sort\nInto the box of things forbidden\nBut the melody stayed hidden\n\n[chorus]\nPata pata dig it out\nFrom the silence and the doubt\nThe groove survived the shipping crate\nArrived a decade late but great\n\n[verse]\nA pressing plant in Soweto\nA bootleg copy in Bamako\nThe music travelled without a stamp\nFrom the township to the camp"},
    {"caption": "Cornelius style Shibuya-kei, Japanese eclectic pop, sample collage, 1990s Tokyo, playful and precise",
     "lyrics": "[verse]\nA bossa nova sample meets\nA breakbeat from the London streets\nA koto phrase from '65\nAll spliced together kept alive\n\n[chorus]\nPoint to point the needle drops\nAcross the globe the music hops\nFrom pressing plant to dollar bin\nTo this exact moment we are in\n\n[verse]\nThe liner notes in Japanese\nA photograph of studio keys\nThe session players never knew\nTheir lick would surface somewhere new"},
    {"caption": "Tinariwen style desert blues, Tamasheq vocal, electric guitar, Saharan grit, rebel music from the sand",
     "lyrics": "[verse]\nThe cassette tape was copied twice\nIn Kidal then in paradise\nI mean Bamako which felt that way\nThe night we heard the rebels play\n\n[chorus]\nDesert blues no record store\nJust the dunes and nothing more\nA guitar plugged into a truck\nThe sound of not believing in luck\n\n[verse]\nThe melody is centuries old\nBefore the borders before the cold\nWar drew the lines across the sand\nThe music moved from hand to hand"},
    {"caption": "Ennio Morricone style, orchestral and electric guitar, Spaghetti Western vocal, haunting and cinematic",
     "lyrics": "[verse]\nThe trumpet echoes off the cliff\nA melody made of what-if\nThe gunfighter squints at the sun\nThe duel is lost before it's begun\n\n[chorus]\nWah wah wah the soundtrack plays\nThrough the dust of ancient days\nA score composed for empty land\nThat anyone can understand\n\n[verse]\nThe harmonica and the strings\nThe loneliest of human things\nA suitcase record store in Rome\nBrings the western wanderer home"},
    {"caption": "Mulatu Astatke style Ethio-jazz, male vocal in Amharic feel, vibraphone and brass, Addis Ababa late night",
     "lyrics": "[verse]\nThe club in Addis had no sign\nJust music pouring out like wine\nThe vibraphone and saxophone\nSpeaking languages unknown\n\n[chorus]\nListen to the space between\nThe notes the West has never seen\nThe scale that fell through every crack\nNow bouncing off the vinyl black\n\n[verse]\nA minor key that isn't minor\nA major that feels even finer\nThe mode they call it tizita\nThe memory inside the star"},
    {"caption": "Cesária Évora style Cape Verdean morna, Portuguese Creole vocal, acoustic guitar, saudade, Atlantic soul",
     "lyrics": "[verse]\nThe barefoot diva on the stage\nA wine glass and a turning page\nOf songs about the ships that left\nAnd those who stayed and those bereft\n\n[chorus]\nSodade sodade the ache\nOf every wave the ocean makes\nBetween the islands and the shore\nThe music asks for nothing more\n\n[verse]\nThe record pressed in Lisbon rain\nArrived in Mindelo again\nA circle drawn across the sea\nThe archaeology of saudade"},
    {"caption": "Bembeya Jazz National style, Guinean guitar, French vocal, 1970s Conakry, state-sponsored Afro-jazz",
     "lyrics": "[verse]\nThe government said play the jazz\nBut make it ours give it pizzazz\nThe kora melody through the amp\nFrom the forest to the presidential camp\n\n[chorus]\nBembeya bembeya the diamond\nThe sound that sparkles off the ground\nOf Guinea, golden, proud and loud\nA nation singing to the crowd\n\n[verse]\nThe vinyl's scratched the sleeve is torn\nBut underneath the sound is born\nAgain each time the needle finds\nThe groove between the border lines"},
    {"caption": "Selda Bağcan style Turkish folk-protest, powerful female vocal, saz and electric bass, 1970s Ankara fire",
     "lyrics": "[verse]\nThe censors took the master tape\nBut someone made a quick escape\nWith a copy in a plastic bag\nThe revolution in a rag\n\n[chorus]\nYıldızlar yıldızlar the stars\nAre burning through the prison bars\nThe song they tried to lock away\nIs on the radio today\n\n[verse]\nAnatolian rock and rage\nA woman's voice against the cage\nThe saz is buzzing like a wire\nCarrying the people's fire"},
]

signal_report_new = [
    # instrumental — 25 new
    "Pan Sonic style harsh minimal techno, Mika Vainio, Finnish cold electronics, brutal sine waves",
    "Einstürzende Neubauten percussion, metal sheets and power tools, Berlin industrial clang",
    "gabber kick drum at 160bpm slowed to 80, distorted bass pulse, Rotterdam concrete",
    "Clark style Warp Records electronics, glitchy and muscular, Sheffield digital maximalism",
    "This Heat style post-punk improv, tape collage, Brixton 1980, proto-industrial experiment",
    "Raime style blackest techno, London 2012, cavernous reverb, two-note dread",
    "Vladislav Delay style, dub techno disintegration, Helsinki fog, click and hiss",
    "Hecker-style noise, extreme digital processing, Editions Mego, laptop concert violence",
    "test-tone broadcast emergency, sine wave and static, civil defense frequency, systemic anxiety",
    "Mark Fell style algorithmic rhythm, Sheffield, generative pattern, inhuman precision",
    "Pharmakon style power electronics, industrial noise, feedback and screaming distortion",
    "Objekt style club music, impossible drum patterns, TT by Objekt energy, dancefloor vertigo",
    "Rashad Becker style, Dial Records electronic, alien textures, unclassifiable and unsettling",
    "broken transmission, shortwave numbers station recording over kick drum, spy-fi tension",
    "Andy Stott style, maximum bass, Demdike Stare cousin, Manchester weight, slow burn",
    "SPK-style early industrial, musique concrète meets punk, 1980 Australia, clatter and hiss",
    "Lorenzo Senni style pointillistic trance, supersaw stabs with no drop, anticipation as content",
    "Lee Gamble style UK rave archaeology, jungle ghost, vapor-memory of breakbeats",
    "Holly Herndon style vocal processing, AI choir, digital humanism, uncanny valley singing",
    "Ryoji Ikeda data-driven sound, pure mathematics as audio, white noise granulation, Tokyo precision",
    "footwork at 160bpm, RP Boo style Chicago, rapid-fire samples, South Side urgency",
    "Ben Frost dark orchestral electronics, Aurora Borealis meets machine, Icelandic brutalism",
    "Container style, lo-fi drum machine industrial, Providence Rhode Island, four-track noise techno",
    "Actress style, foggy electronic abstraction, Werkdiscs, London after midnight, R.I.P. era",
    "sunn O))) wall of guitar drone, earth-shaking sub-bass, monastic robes and amplifier worship",
    # vocal — 10 new
    {"caption": "Savages style post-punk, commanding female vocal, angular bass and drums, Paris meets London, fierce",
     "lyrics": "[verse]\nThe camera's on the camera's on\nSmile for the algorithm's dawn\nYour preferences are someone's yield\nYour face is someone's battlefield\n\n[chorus]\nShut up shut up and listen now\nThe signal tells you when and how\nTo feel to buy to click to share\nYour outrage is their silverware\n\n[verse]\nThe anchor reads the autocue\nThe breaking news is breaking you\nThe cycle spins the cycle feeds\nOn everything the signal breeds"},
    {"caption": "Wire style minimal post-punk, clipped male vocal, two-minute razor songs, 1977 art-punk intelligence",
     "lyrics": "[verse]\nFifteen words is all you need\nTo plant a military seed\nThe communiqué the press release\nThe manufacture of the peace\n\n[chorus]\nMap reference forty-one\nThe report is never done\nNine eight seven six five four\nThe signal at the signal's core\n\n[verse]\nReuters AP the wire feed\nThe minimum the mouth will need\nTo make a sentence out of fact\nAnd still leave nothing quite intact"},
    {"caption": "Sleaford Mods style, spoken-word aggression over minimal beat, Nottingham fury, class-war dispatch",
     "lyrics": "[verse]\nThe rent went up the hours went down\nThe high street's just a charity town\nThe MP's second home costs more\nThan everyone on my entire floor\n\n[chorus]\nSignal report from the ground\nThe truth they never want around\nIt smells like bins and tastes like debt\nThe only news you won't forget\n\n[verse]\nThe food bank queue is down the block\nThe clock-in clock-out punch-the-clock\nThe zero-hours zeroed out\nThat's what the signal's all about"},
    {"caption": "Protomartyr style, baritone post-punk vocal, motorik-influenced drums, Detroit literary, bleak and sharp",
     "lyrics": "[verse]\nThe factory that made the cars\nNow makes the silences and scars\nA city built on what was once\nIs now the subject of the hunt\n\n[chorus]\nUnder the radar under the wire\nAnother correspondent for hire\nThe story writes itself tonight\nIn unemployment's fluorescent light\n\n[verse]\nThe water tastes like infrastructure\nThe headline reads like architecture\nDesigned to hold the weight of lies\nUntil the whole damn building dies"},
    {"caption": "IDLES style, shouted male vocal, dense guitars, Bristol punk energy, vulnerability and rage combined",
     "lyrics": "[verse]\nMy mother worked for thirty years\nFor a pension made of gears\nThat grind the people into paste\nThen tell them not to let it go to waste\n\n[chorus]\nJoy joy joy in the signal\nTruth truth truth in the single\nNote that cuts through all the noise\nThe human sound the human voice\n\n[verse]\nThe NHS the BBC\nThe things they built for you and me\nAre being sold from underneath\nSmile for the camera show your teeth"},
    {"caption": "Depeche Mode style, dark synth-pop, brooding baritone, 1980s cold wave, Berlin era electronic noir",
     "lyrics": "[verse]\nThe policy is pleasure now\nThe screen will tell you when and how\nTo want the thing you didn't need\nDesire manufactured at speed\n\n[chorus]\nEnjoy the silence of the sell\nThe frequency that rings the bell\nInside the pleasure dome of choice\nThere is no signal there's no voice\n\n[verse]\nThe personal is political\nThe digital is ritual\nWe kneel before the algorithm's grace\nAnd offer it our time and face"},
    {"caption": "Dry Cleaning style, spoken female vocal over post-punk, deadpan and surreal, South London art-noise",
     "lyrics": "[verse]\nI read the terms and conditions twice\nThe font was small the price was nice\nMy data went to seven firms\nAll operating within terms\n\n[chorus]\nStrong and stable scratchcard nation\nRefresh the page for new frustration\nThe signal comes in PDF\nI'll read it when there's nothing left\n\n[verse]\nThe chatbot asks me how I feel\nI tell it something almost real\nIt recommends a purchase based\nOn sadness algorithmically traced"},
    {"caption": "Siouxsie and the Banshees style, dramatic female vocal, dark post-punk guitar, 1980 Kaleidoscope energy",
     "lyrics": "[verse]\nBehind the glass the newsroom glows\nFluorescent truths fluorescent woes\nThe teleprompter scrolls the fear\nIn sentences designed to steer\n\n[chorus]\nMonitor monitor on the wall\nWho's the most informed of all\nThe signal splits into a prism\nOf competing catechism\n\n[verse]\nThe anchor's hair does not move once\nThe weather tells the coming months\nOf turbulence both literal\nAnd figuratively political"},
    {"caption": "Squid style, frantic art-punk, dual vocals, polyrhythmic drumming, Brighton chaos, breathless reporting",
     "lyrics": "[verse]\nThe pamphlet and the podcast merge\nInto a democratic dirge\nEveryone's a journalist now\nWith a phone and a furrowed brow\n\n[chorus]\nBreaking breaking broken news\nPick a side pick a side choose\nThe frequency is overloaded\nEverything's already been decoded\n\n[verse]\nA citizen with a camera phone\nIs never quite entirely alone\nThe footage goes from hand to cloud\nThe truth is just whatever's loud"},
    {"caption": "Young Marble Giants style, minimal post-punk, quiet female vocal, drum machine, razor-thin guitar, Cardiff calm",
     "lyrics": "[verse]\nThe final day of ordinary\nWas a Tuesday in February\nThe headline changed the temperature\nOf every conversation's furniture\n\n[chorus]\nColossal youth and the report\nCame in from every kind of court\nThe signal barely there but true\nA whisper that the whole world knew\n\n[verse]\nI turned the radio down low\nTo hear the things they wouldn't show\nThe quietest frequency survived\nThe loudest barely stayed alive"},
]

the_groove_lab_new = [
    # instrumental — 25 new
    "Meters style New Orleans funk, Zigaboo drumming, greasy Cissy Strut groove, 1969 swamp funk",
    "Mtume Juicy Fruit style, 1980s R&B electro-funk, drum machine and bass synth, satin smooth",
    "Budos Band style Afro-soul instrumental, Staten Island meets Lagos, heavy brass and drums",
    "Daptone Records style, Sharon Jones band, retro soul, analog warmth, Brooklyn revival funk",
    "boogie roller-rink style, 1982, synth bass and handclaps, skate floor groove, Saturday night",
    "Lee Fields deep funk, raw soul, heavy drums and organ, 2am set, sweat and grit",
    "Mulatu meets Headhunters, Ethio-jazz funk hybrid, vibraphone and clavinet, 1974 imaginary session",
    "go-go music, Chuck Brown style, DC percussion heavy, conga and timbale, block party energy",
    "broken beat, 4hero influence, West London syncopation, complex and danceable, 2003",
    "Pleasure style Portland funk, horn section and slap bass, 1970s Pacific Northwest groove",
    "Fania All-Stars style salsa, Larry Harlow piano, Nuyorican brass, 1970s Latin boogaloo",
    "acid jazz, Brand New Heavies style, 1990s London, jazz-funk with house beat, optimistic",
    "Tower of Power horn-driven funk, Oakland brass precision, tight and punchy, 1973",
    "Kool and the Gang Jungle Boogie era, heavy funk, rhythm guitar chops, 1974 dancefloor fire",
    "Soulquarians session, Questlove drums, Erykah and D'Angelo adjacent, Electric Lady Studios vibe",
    "Cameroonian makossa, Manu Dibango influence, saxophone and bass guitar, Douala groove",
    "soca, Mighty Sparrow energy, Trinidad carnival, brass and rhythm section, wine and jam",
    "Stevie Wonder Innervisions era, clavinet and Moog, warm and political, 1973 genius funk",
    "Eddie Palmieri Latin jazz-funk, heavy piano montuno, Nuyorican salsa meets hard bop",
    "Minneapolis sound, Prince 1999 era, Linn drum and synth bass, purple funk, 1982",
    "Ohio Players Fire era, heavy wah guitar and horns, 1974 rubber-band funk",
    "Leon Bridges style retro-soul instrumental, warm guitar and organ, Fort Worth, Sunday afternoon",
    "Cymande Brothers on the Slide, British Afro-funk, gentle and deep, 1973 underground London",
    "Gil Scott-Heron groove, spoken word adjacent funk, congas and Rhodes, 1974 political soul",
    "Vulfpeck low-volume funk, intentionally quiet groove, bass and drums, Michigan minimalism",
    # vocal — 10 new
    {"caption": "James Brown style raw funk, energetic male vocal, horn stabs, screaming soul, hardest working groove",
     "lyrics": "[verse]\nGet up off of that thing I said\nThe groove is rising from the dead\nThe one and the three are where we live\nThe downbeat's got so much to give\n\n[chorus]\nHit me hit me with the funk\nI was in a two-year slump\nBut the bass came back around\nAnd my feet found the ground\n\n[verse]\nThe drummer's in the pocket deep\nSo deep it puts the rest to sleep\nExcept the ones who feel the pull\nThe dancefloor beautifully full"},
    {"caption": "Chaka Khan style, powerful female vocal, disco-funk energy, brass and strings, I Feel For You era",
     "lyrics": "[verse]\nThe mirror ball is spinning light\nAcross the faces Friday night\nThe bass is walking through the crowd\nThe horn section is getting loud\n\n[chorus]\nEvery woman every man\nDo it do it while you can\nThe groove don't wait the groove don't stall\nThe groove is here for one and all\n\n[verse]\nThe DJ fades the record in\nThe sweetest kind of discipline\nIs knowing when to let it ride\nAnd when to take it for a slide"},
    {"caption": "Anderson .Paak style, raspy male vocal, drumming and singing, West Coast neo-soul funk, Oxnard sunshine",
     "lyrics": "[verse]\nSatin sheets and tangerines\nThe California in-between\nOf Sunday morning Monday dread\nBut the funk just pulled me back to bed\n\n[chorus]\nYes lawd the groove is here\nPut it in your face put it in your ear\nThe snare is cracking like a whip\nAnd everybody start to dip\n\n[verse]\nMy grandma's records on the shelf\nI learned to drum by playing them myself\nThe Isley Brothers taught me feel\nThe groove is just what's real"},
    {"caption": "Janelle Monáe style, Afrofuturist funk, energetic female vocal, synth and guitar, android liberation",
     "lyrics": "[verse]\nElectric sheep are on the beat\nThe android's dancing on her feet\nThe future funk is chrome and gold\nA story waiting to be told\n\n[chorus]\nTightrope walking on the bass\nAnother time another place\nThe groove transcends the century\nFrom Motown to the Milky Way free\n\n[verse]\nPrince left a manual behind\nIt says the funk is state of mind\nSo plug in baby turn it up\nThe future's overflowing cup"},
    {"caption": "Betty Davis style raw funk, fierce female vocal, heavy guitar and bass, 1970s nasty groove, unapologetic",
     "lyrics": "[verse]\nI walked in and the room got hot\nThe bass line gave me everything it got\nThe wah guitar is dripping wet\nThis is a groove you won't forget\n\n[chorus]\nNasty nasty that's the word\nThe dirtiest clean sound you've heard\nThe funk don't ask for your permission\nIt's a calling not a mission\n\n[verse]\nThe conga player's lost in time\nThe organ's committing a perfect crime\nOf sounding both sacred and profane\nThe groove lab running through my veins"},
    {"caption": "Earth Wind and Fire style, joyful male vocal harmonies, kalimba and horns, cosmic disco-funk, September energy",
     "lyrics": "[verse]\nThe stars aligned above the club\nThe bass was deep enough to scrub\nThe worry off of every face\nThe universe is just this place\n\n[chorus]\nDo you remember when the groove\nFirst taught your body how to move\nThat moment when the music spoke\nAnd something beautiful awoke\n\n[verse]\nThe horn section is testifying\nThe string section is electrifying\nThe rhythm section holds it down\nThe groove lab is the best in town"},
    {"caption": "Thundercat style, virtuosic bass vocal, playful falsetto, jazz-funk absurdity, LA weirdness, warm and strange",
     "lyrics": "[verse]\nMy cat is sitting on the amp\nThe studio is slightly damp\nThe bass is tuned to something odd\nA frequency approved by God\n\n[chorus]\nFunky funky astronaut\nPlaying every note I've got\nSix strings of bass insanity\nThe groove defying gravity\n\n[verse]\nI ate a burrito and a dream\nThe session's somewhere in between\nGenius and absurdity\nWhich is the same thing don't you see"},
    {"caption": "Sharon Jones style, Daptone soul, powerful female vocal, retro arrangement, Brooklyn warmth, 100 proof",
     "lyrics": "[verse]\nThe studio on Troutman Street\nIs where the past and present meet\nThe tape machine is running hot\nWe play it once that's all we got\n\n[chorus]\nGive the drummer some right now\nLet the bass line show you how\nTo feel the thing you came to feel\nThe analog the warm the real\n\n[verse]\nNo auto-tune no studio tricks\nJust musicians and their picks\nAnd sticks and keys and vocal cords\nThe groove is made of honest chords"},
    {"caption": "Childish Gambino Awaken style, soulful male vocal, gospel choir, funk bass, Afrofuturist ceremony",
     "lyrics": "[verse]\nThe congregation of the beat\nIs gathered on a Harlem street\nThe sermon is a bass line low\nThe choir is the afterglow\n\n[chorus]\nThis is church this is the lab\nWhere we turn the hurt to fab\nThe groove is sacrament tonight\nTransforming darkness into light\n\n[verse]\nThe Hammond's crying hallelujah\nThe snare drum's saying I knew ya\nBefore the pain before the song\nThe groove is where we all belong"},
    {"caption": "Lizzo style, exuberant female vocal with flute, body-positive funk, Minneapolis energy, joyful and defiant",
     "lyrics": "[verse]\nI woke up feeling like a million bucks\nPut on a record full of funk and strut\nThe flute is playing something freaky sweet\nMy neighbors knocking cause I'm stomping feet\n\n[chorus]\nGroove is self-love set to beat\nGroove is dancing down the street\nGroove don't care about your size\nGroove is the look in your eyes\n\n[verse]\nThe band is tight the horns are hot\nI brought everything everything I got\nTo the lab tonight and I won't leave\nUntil the funk has made me believe"},
]

crosswire_new = [
    # instrumental — 25 new
    "throat singing meets modular synthesizer, Tuvan overtones through Eurorack, tundra and circuit board",
    "Cuban son montuno meets UK jungle breakbeat, tres guitar over amen break, 160bpm rumba",
    "Malian ngoni meets Nashville pedal steel, West African griot and country twang, unlikely cousins",
    "Persian tar meets delta blues slide guitar, microtonal bends in conversation, Isfahan meets Clarksdale",
    "Appalachian banjo meets Japanese shamisen, plucked string duel, mountain meets zen garden",
    "West African balafon meets Javanese gamelan, wooden keys meet bronze, pentatonic argument",
    "accordion tango meets drum and bass, Buenos Aires meets Bristol, Piazzolla on breakbeats",
    "didgeridoo meets techno kick drum, Aboriginal drone meets Berlin four-on-the-floor, ancient pulse",
    "Scottish bagpipes meet Indian shehnai, two reeded traditions screaming at each other beautifully",
    "Polynesian log drum meets Detroit 808, Pacific rhythm meets Motor City machine, island-industrial",
    "Chinese pipa meets flamenco guitar, rapid tremolo conversation, silk road meets silk strings",
    "West African talking drum meets Roland TR-909, Yoruba and house music, sacred dancefloor",
    "Byzantine chant meets dub reggae, monastery echo meets Kingston reverb, sacred bass",
    "Norwegian Hardanger fiddle meets Indian sarangi, sympathetic strings both, Nordic-Hindustani resonance",
    "Okinawan sanshin meets surf guitar, Pacific island rockabilly, 1960s meets 16th century",
    "South Indian mridangam meets jazz brushed drums, Carnatic meets Blue Note, conversation of hands",
    "Andean panpipe ensemble meets electronic ambient, Cusco meets Cologne, altitude and synthesis",
    "Arabic maqam meets twelve-tone serialism, quarter-tones meeting atonality, mathematical beauty",
    "Portuguese fado guitar meets Hawaiian slack-key, two Atlantic islands, saudade meets aloha",
    "Afrobeat polyrhythm meets minimalist phasing, Fela meets Reich, Lagos repetition experiment",
    "Tibetan singing bowls meet glass harmonica, metal and crystal drones, meditation meets séance",
    "ska organ shuffle meets Ethio-jazz scales, Kingston meets Addis, pentatonic rocksteady",
    "Moroccan guembri bass meets dub step wobble, gnawa meets digital London, trance-step",
    "Mexican son jarocho meets Balkan brass, Veracruz meets Belgrade, wedding crash",
    "Korean gayageum meets prepared piano, 12 silk strings meet bolts and screws, Seoul meets New York",
    # vocal — 10 new
    {"caption": "Tinariwen meets Sonic Youth, desert blues vocal, noise guitar, Saharan no wave, raw and hypnotic",
     "lyrics": "[verse]\nThe guitar is tuned to the desert wind\nThe amplifier's patience wearing thin\nTwo continents collide in sand\nA sound nobody planned\n\n[chorus]\nCross the wire cross the line\nEvery frequency's a vine\nGrowing tangled growing wild\nEvery genre is a child\n\n[verse]\nNew York City meets the Sahel\nA story only sound can tell\nThe feedback and the pentatonic\nMerge into something supersonic"},
    {"caption": "Bomba Estereo style, Colombian electro-cumbia, female vocal, synthesizer and gaita, Caribbean futurism",
     "lyrics": "[verse]\nThe gaita flute went digital\nThe cumbia got political\nThe bass dropped like a coconut\nOn every border every rut\n\n[chorus]\nSelva selva concrete jungle\nEvery root begins to rumble\nWhen the old and new collide\nThere's nowhere left for pride to hide\n\n[verse]\nBogotá Berlin Dakar\nEvery city has a scar\nThat opens when the music plays\nThe hybrid sound of modern days"},
    {"caption": "Yma Sumac meets Björk, extreme vocal range, Peruvian-Icelandic fusion, operatic and electronic, mythic",
     "lyrics": "[verse]\nFive octaves span the Andes high\nTo where the Arctic meets the sky\nA voice that shouldn't be this wide\nContaining multitudes inside\n\n[chorus]\nI am the volcano and the glacier\nThe ancient and the brand-new nature\nMy voice is where the tectonic plates\nSlide past each other and create\n\n[verse]\nThe condor and the puffin sing\nA duet of impossible things\nOne born of fire one of ice\nMeeting once and meeting twice"},
    {"caption": "Dengue Fever style, Cambodian psych-rock, Khmer female vocal over garage rock, Phnom Penh meets California",
     "lyrics": "[verse]\nThe Farfisa organ from the West\nMeets the voice that knows it best\nA melody from Battambang\nOver a guitar that goes twang\n\n[chorus]\nTwo histories in one room\nMaking something else in bloom\nThe war destroyed the tapes but not\nThe melody the singer got\n\n[verse]\nLong Beach and the Mekong River\nBoth delivering a shiver\nOf recognition when you hear\nThe past and future crystal clear"},
    {"caption": "Ry Cooder and Ali Farka Touré style, American-Malian guitar duet, male vocal, roots conversation",
     "lyrics": "[verse]\nYour blues sound like my blues he said\nThe river connects the riverbed\nFrom Mississippi to the Niger\nThe guitar gets a little wider\n\n[chorus]\nThe wire that crosses every ocean\nCarries music like devotion\nFrom one porch to another yard\nThe easiest thing and the most hard\n\n[verse]\nA pentatonic secret code\nThat every tributary flowed\nFrom the same mountain the same rain\nThe crosswire singing through the pain"},
    {"caption": "Natacha Atlas style, Arabic-electronic fusion, powerful female vocal, Egyptian meets UK dance, belly-bass",
     "lyrics": "[verse]\nThe tabla and the TR-808\nAre arguing about the fate\nOf rhythm in the modern world\nWhile Arabic quarter-tones are hurled\n\n[chorus]\nYallah yallah to the floor\nThe crosswire opens every door\nBetween the minaret and the bass bin\nA new prayer is about to begin\n\n[verse]\nCairo's streets meet London's rain\nThe oud plugged into the mainframe\nThe dancer and the DJ merge\nOn the edge of every surge"},
    {"caption": "Konono No. 1 style, amplified thumb piano, distorted Congolese trance, electronic dance-ritual, Kinshasa DIY",
     "lyrics": "[verse]\nThe amplifier's made of tin\nThe speaker's made of anything\nA car part and a microphone\nPlugged into the megaphone\n\n[chorus]\nLikembe likembe make it loud\nLoud enough to draw a crowd\nThe spirit and the speaker wire\nAre the same electric fire\n\n[verse]\nKinshasa's suburbs shake the ground\nWith the most recycled sound\nA trance that's older than the city\nMade of junkyard and made pretty"},
    {"caption": "Dakhabrakha style, Ukrainian folk meets world, four-voice harmony, tabla and cello, Carpathian-global",
     "lyrics": "[verse]\nThe Carpathian mountains meet Calcutta\nThrough a melody of bread and butter\nFour voices weaving like a braid\nOf every sound that's ever played\n\n[chorus]\nHey hey the steppe is wide\nEnough for every song inside\nUkrainian Bengali Brazilian too\nThe folk song made entirely new\n\n[verse]\nThe cello bows the tabla speaks\nThe harmony ascends the peaks\nOf every border ever drawn\nAnd plants a song upon the lawn"},
    {"caption": "Las Cafeteras style, Chicano son jarocho meets hip-hop, bilingual vocal, jarana and beatbox, East LA",
     "lyrics": "[verse]\nLa bamba meets the boulevard\nThe tarima stomping in the yard\nA zapateo and a breakbeat\nThe oldest and the newest feet\n\n[chorus]\nCruzando cruzando the wire\nThe son jarocho meets the fire\nOf hip-hop born in the Bronx\nNow living in the Aztec fonts\n\n[verse]\nVerse in Spanish verse in English\nThe language shifts like something skittish\nBut the rhythm stays the rhythm stays\nAcross the decades through the haze"},
    {"caption": "Anoushka Shankar meets Thievery Corporation, sitar over dub-electronic, Indo-American lounge, midnight embassy",
     "lyrics": "[verse]\nThe embassy party after hours\nThe sitar through the cooling towers\nA raga meets a dub delay\nDiplomacy of beat and sway\n\n[chorus]\nEvery border has a frequency\nThat vibrates at the same degree\nThe crosswire finds it every time\nThe undertone beneath the crime\n\n[verse]\nThe tabla player from Kolkata\nThe DJ from the District charter\nNod at each other through the smoke\nAcknowledging the ancient joke"},
]

listener_hours_new = [
    # instrumental — 25 new
    "accordion and fiddle, Cajun two-step, Louisiana bayou porch, warm and communal, zydeco adjacent",
    "thumb piano kalimba solo, gentle African lullaby feel, intimate and reassuring, maternal warmth",
    "lap steel guitar and ukulele, Pacific island evening, Hawaiian mele, sunset communal",
    "piano bar style, Billy Joel influence, late-night requests, everyone singing along",
    "African-American gospel piano, church basement, Wednesday rehearsal, communal and earnest",
    "Portuguese guitarra solo, Fado tradition, intimate Lisbon tavern, one candle, shared tears",
    "bandoneon tango, Buenos Aires milonga, couples dancing, intimate and passionate, shared breath",
    "West African griot kora, evening storytelling, village gathering, Manding hospitality",
    "old-time string band, fiddle and guitar, Appalachian front porch, neighbors and fireflies",
    "harmonica and acoustic guitar, folk-blues duo, small venue, between-songs laughter",
    "Arabic oud and riq, intimate maqam, North African tea house, shared silence and music",
    "Scottish ceilidh band, accordion and fiddle, village hall warmth, everyone dancing",
    "Venezuelan joropo, harp and maracas, llanos campfire, plains music under stars",
    "New Zealand taonga pūoro, traditional Māori instruments, intimate and sacred, communal breath",
    "Afro-Peruvian cajón and guitar, criolla music, Lima peña, stomping and singing together",
    "Brazilian forró, accordion and triangle, Nordeste dance, intimate and joyful, sweat and joy",
    "Irish concertina solo, slow air, cottage by the hearth, turf fire and rain outside",
    "Malagasy valiha, Madagascan tube zither, gentle and bright, village evening, communal sharing",
    "Swedish nyckelharpa, folk polska dance tune, Dalarna midsummer evening, gentle and ancient",
    "klezmer clarinet solo, celebratory and melancholic, Eastern European wedding, bittersweet joy",
    "sitar and tabla duet, Indian classical evening raga, intimate and devotional, shared listening",
    "South African maskanda guitar, Zulu acoustic tradition, storytelling and praise, communal and warm",
    "Okinawan sanshin and voice, island evening song, Ryukyuan tradition, sea breeze and lanterns",
    "bluegrass mandolin and guitar, close harmony, mountain church, Sunday evening, communal faith",
    "Persian kamancheh, Iranian bowed string, evening gathering, tea and poetry, intimate circles",
    # vocal — 10 new
    {"caption": "Dolly Parton style, warm country female vocal, acoustic guitar, Appalachian storytelling, front porch wisdom",
     "lyrics": "[verse]\nA letter came from Knoxville town\nFrom a woman whose mama just sat down\nAt the radio and didn't move\nFor three whole hours in the groove\n\n[chorus]\nThank you for the company\nWhen the house gets quiet, see\nThe radio's a kind of friend\nThat stays with you until the end\n\n[verse]\nShe said Mama doesn't talk much now\nBut when your station played somehow\nShe hummed along and tapped her knee\nAnd for a moment she was free"},
    {"caption": "Sam Cooke style, warm tenor soul, gentle guitar, A Change Is Gonna Come intimacy, communal hope",
     "lyrics": "[verse]\nA letter from the overnight shift\nSays your voice is such a gift\nWhen the warehouse floor is cold\nAnd the morning's getting old\n\n[chorus]\nWe are the listeners we are here\nIn the dark year after year\nThe radio connects the dots\nBetween the haves and have-nots\n\n[verse]\nHe works from midnight until six\nWith headphones and a thermos mix\nOf coffee and the will to stay\nAlive until the break of day"},
    {"caption": "Aimee Mann style, clear female vocal, piano and strings, intelligent pop, bittersweet and knowing",
     "lyrics": "[verse]\nYou wrote to say you almost quit\nThen heard a song that made you sit\nBack down and try one more time through\nThe paperwork that's burying you\n\n[chorus]\nSometimes a song at the right time\nIs the difference between the climb\nAnd the fall and you never know\nWhich frequency will stop the blow\n\n[verse]\nSo this one's for the barely there\nThe hanging on by just a hair\nThe ones who need a voice to say\nYou're going to be okay today"},
    {"caption": "Woody Guthrie style, rough male vocal, acoustic guitar, dust bowl folk, people's music, communal singing",
     "lyrics": "[verse]\nThis radio was made for you and me\nFrom the redwood forest to the shining sea\nA trucker called from I-95\nTo say this station keeps him alive\n\n[chorus]\nThis land is your land of the dial\nEvery frequency every mile\nBelongs to everyone who tunes\nTo the midnight afternoon\n\n[verse]\nA welder and a nurse agree\nThat 3am is when they need\nA human voice inside the air\nJust to know that someone's there"},
    {"caption": "Buena Vista Social Club style, aged Cuban male vocal, acoustic guitar, Havana warmth, timeless and gracious",
     "lyrics": "[verse]\nAn old man writes from Cienfuegos\nHis radio has seen better days though\nThe antenna's bent the speaker cracks\nBut still the music comes right back\n\n[chorus]\nCompay amigo through the wire\nThe signal crossed the gulf of fire\nBetween your island and my shore\nAnd opened up a brand new door\n\n[verse]\nHe says the bolero at eleven\nReminds him of his wife in heaven\nThe song she danced to in their yard\nBeneath the mango growing hard"},
    {"caption": "Lauryn Hill style, soulful female vocal, acoustic guitar, intimate and prophetic, Miseducation warmth",
     "lyrics": "[verse]\nA teenager writes in pencil thin\nSays the world is closing in\nBut the signal on her clock radio\nReminds her there's somewhere to go\n\n[chorus]\nEverything is everything\nThe listener the voice that sings\nConnected by the frequency\nOf radical simplicity\n\n[verse]\nShe says she listens every night\nUnderneath the bathroom light\nThe only place she has alone\nThe radio a second home"},
    {"caption": "Leonard Cohen late-era style, deep spoken-sung baritone, synthesizer and choir, wise and surrendered",
     "lyrics": "[verse]\nA postcard from a prison cell\nJust two lines but two that tell\nThe whole cathedral of a life\nThe husband and the former wife\n\n[chorus]\nThere is a frequency that's cracked\nThat lets the wounded signal back\nInto the world of those who care\nThe listener hours are a prayer\n\n[verse]\nHe says the radio at night\nIs the only thing that's right\nIn a place where nothing is\nThe signal is the bridge there is"},
    {"caption": "Vashti Bunyan style, whisper-gentle female folk vocal, acoustic guitar, pastoral and intimate, just-between-us",
     "lyrics": "[verse]\nA letter written on a leaf\nWell nearly that thin with grief\nAnd beauty in equal measure\nA listener's most private treasure\n\n[chorus]\nJust looking for a diamond day\nA signal on a Saturday\nThat makes the kitchen feel like home\nAnd reminds me I'm not alone\n\n[verse]\nShe lives beside a railway track\nThe trains go out the trains come back\nBut the radio stays perfectly still\nA voice upon her windowsill"},
    {"caption": "Richie Havens style, rhythmic acoustic guitar, warm urgent male vocal, Woodstock energy, communal spirit",
     "lyrics": "[verse]\nSometimes I wonder who you are\nOut there in your truck or car\nOr lying on a hospital bed\nOr sitting up cause you can't find your head\n\n[chorus]\nFreedom freedom in the dial\nStay with me another mile\nAnother hour another song\nThe listener hours all night long\n\n[verse]\nA mother writes about her son\nWho listens when the chemo's done\nHe says the voices in the dark\nAre like a match are like a spark"},
    {"caption": "Bonnie Raitt style, warm raspy female vocal, slide guitar, blues-folk tenderness, lived-in and generous",
     "lyrics": "[verse]\nHoney let me read this one\nFrom a woman in Saskatchewan\nShe drives the grain roads all alone\nWith this station as her cornerstone\n\n[chorus]\nI can't give you anything but love\nAnd a frequency from above\nThe prairie and the radio tower\nKeep her company every hour\n\n[verse]\nShe says the winter gets so long\nBut there's always one more song\nBetween the silence and the snow\nThat reminds her of the things she knows"},
]
