bumper_styles:
- ambient
- jazz
- soul
- downtempo
- indie
- electronic
- folk
- rock
- pop
source_types:
- id: url
  name: Web URL
  category: web
- id: reddit_subreddit
  name: Reddit Subreddit
  category: reddit
- id: reddit_thread
  name: Reddit Thread
  category: reddit
- id: youtube_channel
  name: YouTube Channel
  category: youtube
- id: youtube_playlist
  name: YouTube Playlist
  category: youtube
- id: youtube_video
  name: YouTube Video
  category: youtube
- id: rss
  name: RSS Feed
  category: feed
